name: Create and close Jira ticket for each commit

on:
  push:
    branches: [ main ]

permissions: read-all

jobs:
  create_and_close_ticket:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      repository-projects: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create ticket
        env:
          JIRA_HOST: ${{ secrets.JIRA_HOST }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT: <PROJECT_KEY>

        run: |
          git log --oneline --no-merges ${{ github.event.before }}..${{ github.event.after }} |
          while read sha message; do
            response=$(curl -D- -u "${JIRA_EMAIL}:${JIRA_API_TOKEN}" \
            -X POST \
            -H "Content-Type: application/json" \
            "${JIRA_HOST}/rest/api/3/issue/" \
            -d @- <<EOF
            {
              "fields": {
                "project": {"key": "${JIRA_PROJECT}"},
                "summary": "${message}",
                "description": "Commit SHA: ${sha}",
                "issuetype": {"name": "Bug"}
              }
            }
            EOF
            )
            key=$(echo "${response}" | grep -Eo '"key":"[A-Z]+-[0-9]+"' | cut -d':' -f2 | tr -d '"')
            echo "Created Jira ticket ${key} for commit ${sha}"
            echo "issue_key=${key}" >> $GITHUB_OUTPUT
          done
        id: create-ticket
      - name: Close ticket
        if: always()
        env:
          JIRA_HOST: ${{ secrets.JIRA_HOST }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          curl -D- -u "${JIRA_EMAIL}:${JIRA_API_TOKEN}" \
            -X POST \
            -H "Content-Type: application/json" \
            "${JIRA_HOST}/rest/api/2/issue/${{ steps.create-ticket.outputs.issue_key }}/transitions" \
            -d '{"transition": {"id": "2"}}'
