name: Pytest Workflow

on: [push]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  pytest:
    runs-on: [self-hosted, Ubuntu, Common]
    name: Run Pytest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{secrets.PAT || secrets.GITHUB_TOKEN}}
          fetch-depth: 2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install e98-datamodels --extra-index-url https://dl.cloudsmith.io/${{ secrets.PYPITOKEN }}/1898-and-co/data-models/python/simple/ && pip install .[dev] && pip install httpx mongomock pytest pytest-md pytest-emoji
      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          custom-arguments: "-q"
          click-to-expand: true
          report-title: "Test Report"
